### ISSUE TITLE
TUTORIAL - Tutorial doesnt work with customized controls

### ISSUE THREAD

**Issue by FlorianStronk** [koyoki/fof-issues#1]
This was brought up by a new player who customized controls before starting the tutorial. Once you move the shooting button for example, the turorial instructions dont show where the actual button is , but where the defualt button is.

**Comment by TarekA112** [comment]
Issue has been partly fixed. 
All customizable buttons are now suited for tutorial fingerprint demonstration **except for** crouch/prone button.
See BUG 24.
