### ISSUE TITLE
Iphone6 Resolution issue in multiplayer loading screen

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#10]
V 1.1.6
**Tested on Iphone6 NOT Iphone6s**
Not clear on pic, check on device. Thin white line all across left edge of screen.
![img_1799](https://cloud.githubusercontent.com/assets/17575376/13441757/cf35f5fc-dff0-11e5-96f4-eb833d862821.PNG)

**Comment by jorgebarredo** [comment]
Should be fixed on V1.1.8

**Comment by TarekA112** [comment]
No longer appears on iphone6 loading screen.
Fixed in v1.1.9
