### ISSUE TITLE
Control Settings - Button "Reset to Default" does not reset all changed settings.

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#101]
![img_4118 1](https://cloud.githubusercontent.com/assets/17575376/16686099/a64c9732-4507-11e6-8eda-2eef457e03c6.PNG)
In the control settings, the “Reset to Default" button only resets the  changes made to the button positioning. It does not reset the changes made to the enable/disable options shown above. 
Please close if this is intentional.

**Comment by bfield** [comment]
I have made many changes to this screen, changes are in develop branch awaiting a build:

-- Reset Button now resets checkboxes.
-- Fixed bug where if the joystick is moved manually to the opposite side, the in game play area does not update
-- Hide the "Swap move & turn" button when the joystick is active as they joystick now controls move area
-- Moved the joystick to the play area if "swap move & turn" button is pressed and the joystick is turned on again. (at the moment the new positioning of the joystick is a mirror of where it was last,)

NOT DONE
Moved the sensitivity slider to the controls screen. Doing so looks fine on all the preset screens however the custom controls screen becomes very overcrowded. Especially on smaller devices.

**Comment by DanielZ15** [comment]
Great stuff Brent. You can go ahead and put the sensitivity slider in the controls screen. Don't worry about the esthetics, it will all change anyways with the new UI. Tarek, please go ahead and do your QA for this that it's all working and if so close the issue.

**Comment by bfield** [comment]
i have put the sensitivity slider into the controls screen, and i have put a copy of the game on the Sony Xeperia tablet, to be QA'd (on Tarek's desk)

**Comment by TarekA112** [comment]
- "RESET TO DEFAULT" button now now resets all changes on settings screen. fixed
-
