### ISSUE TITLE
Cannot select type of soldier in menu screen

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#102]
Could only select rifleman, was unable to select alternative sniper unit until i cleared my device data.

**Comment by DanielZ15** [comment]
Changing to medium priority, we can only have 5 high priority at any given time. This is next in line

**Comment by DanielZ15** [comment]
This happens after upgrading to 1970s, stuck on rifleman

**Comment by davidhasovic** [comment]
Rob could fix this, it's super annoying

**Comment by DanielZ15** [comment]
Limited to first look version, removing as is low priority and was fixed server side
