### ISSUE TITLE
Cross hair in view mode. 

### ISSUE THREAD

**Issue by jorgebarredo** [koyoki/fof-issues#103]
I was playing sniper, I was scoped in and I was killed. 
The cross hair is stuck where I was aiming to, and still be able to see it if you pan around to this position.

**Comment by jorgebarredo** [comment]
I tried to reproduce it, and I could not.

**Comment by TarekA112** [comment]
When you die and go to post death player view mode, your cross hair is still visible in view mode.

**Comment by DanielZ15** [comment]
I've had this as well in iOS. The crosshair is stuck on the screen, but only if you look in a certain direction, as if it was in 3D space

**Comment by rjkward** [comment]
I have tried to recreate this bug and have been unable to do so. Both sniper and rifleman scoped and unscoped.

**Comment by DanielZ15** [comment]
Ok, closing this issue for now. If it pops back up, I'll reopen it.
