### ISSUE TITLE
Control Settings - regular right/left handed setting has joystick error

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#105]
When you switch your controls to the regular preset "right/left handed" settings, your joystick is too low on the screen which penalise you especially if you are trying to move back.

Basically does not give your thumb enough room to manoeuver.

Obviously, the smaller the screen the bigger the problem.

**Comment by DanielZ15** [comment]
This is not a bug, more of a feature. The whole area of the joystick is still touchable, and we need to communicate this to the player.
