### ISSUE TITLE
Z-Fighting for objects which are far away when scoped in

### ISSUE THREAD

**Issue by DanielZ15** [koyoki/fof-issues#114]
This started to happen when we changed the near clip pane of the scope camera to 0.05. Jorge is aware of this issue.

**Comment by davidhasovic** [comment]
Dante,

Did you not say that this was to do with having duplicates, if so, I hope that Florian will sort this out?

**Comment by DanielZ15** [comment]
This is different. It's happening between different objects as well. It makes sense that this would happen when the near clip pane of the camera is made smaller due to floating point inaccuracies/rounding.

**Comment by DanielZ15** [comment]
Moving this to "High" to put it up in the priority list, replacing a fixed and closed high priority bug.

**Comment by DanielZ15** [comment]
Also related to this, we need to move the 3rd person camera clip pane to 0.01 and create a similar solution for 3rd person. This would also avoid the following:
![capture1](https://cloud.githubusercontent.com/assets/12484473/17409682/2e3408a4-5a68-11e6-95ad-02642f36e114.PNG)
