### ISSUE TITLE
King of the Hill mode - draw + countdown

### ISSUE THREAD

**Issue by DanielZ15** [koyoki/fof-issues#115]
Countdown in King of the Hill should count down, not up - from 4:00 minutes down.
There is a victory/defeat scenario when:
- A team manages to capture the capture zone
- A team kills all enemy players
(whichever comes first)

Any other scenario is a draw if the countdown has run out.

**Comment by jorgebarredo** [comment]
We don't have draw at the moment. We need to change how trophies work in several places (server and client side). We also need new assets for draw in the victory screen and so on.

I think this is more a feature than a bug.

**Comment by TarekA112** [comment]
https://trello.com/c/NbxngZ8O

**Comment by davidhasovic** [comment]
This is a task
