### ISSUE TITLE
Often stuck on loading screen at "Logging in..." step

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#124]
Cannot replicate this issue everytime but very often after session has ended, you hit "battle" button in menu screen, you then get stuck on the loading screen at "logging in.." step.
Happens approx 1 in 4 times.
![img_0089](https://cloud.githubusercontent.com/assets/17575376/17552195/55885094-5ef6-11e6-9509-08873bdcd3fc.jpg)
![img_0085](https://cloud.githubusercontent.com/assets/17575376/17552200/57c55cee-5ef6-11e6-801b-0de14692bdf8.jpg)

**Comment by davidhasovic** [comment]
This is somewhat strange. There is no networking involved here (to my knowledge).
The only type of internet that is happening is HTTP.
I, therefore, imagine this is is either to do with a temporary loss of internet or the HTTP micro service being down for a short period of time.

Would be cool if you did some more testing and wrote down number of attempts and number of failures and the precise times of failures. Also let me know before you test this so i can start watching the logs.

This might inform us as to why this is happening.

**Comment by TarekA112** [comment]
Most probable cause is disconnections during loading process:
Meaning when/if you momentarily disconnect for whatever reason during the loading process, there is no process to reconnect you at this stage of the game (according to Andy), which means you can't go any further and you're stuck on that loading screen until you restart App.  This needs additional code according to DEV.

**Comment by TarekA112** [comment]
Fixed
