### ISSUE TITLE
3G play , rising ping and phone switch off, unable to join.

### ISSUE THREAD

**Issue by FlorianStronk** [koyoki/fof-issues#141]
I played on 3G today. I first wasnt able to join, I had connected to the queue with 2 bars 3G, then the game said "starting"  but I was never connected to the lobby.
When I then checked my networking status I saw the networking quality had dropped.
There should have been a wanring in game telling me that.

I moved into 3bar 3G territory and got into a game and the following haapened:
1. game started with ping of 150, while moving it started going up, 200, 500, 7000 etc and at some point I got the reconnection countdown and was put back into the game at low ping. Then the same thing happened (ping going up) and then my phone switched off.
I restarted phone and saw I had still 17% power left.

I then tried joining subsequent matches (4G coverage by then) and had the same experience as above (queuing  enough players show, game counts down everyone else gets removed from queue and I get put into the post victory screen menu (the main artwork with contact us button).

I was only able to get into a game with the device when I was back at home in Wifi.

![image](https://cloud.githubusercontent.com/assets/6587346/18231066/be26b6d2-72a5-11e6-97d2-e441264f2cc3.png)
![image](https://cloud.githubusercontent.com/assets/6587346/18231067/c4cb97c8-72a5-11e6-9787-8ad0f0d5ddb3.png)

**Comment by davidhasovic** [comment]
Cool, let's replicate it in the office and then we can take a look

**Comment by TarekA112** [comment]
Open Bug.
Need to be moved to Trello
