### ISSUE TITLE
Two players cant start 1.1.7

### ISSUE THREAD

**Issue by FlorianStronk** [koyoki/fof-issues#18]
Both Toad and CaptainChaos cant get into 1.1.7. 

After lading bundles, game hangs on loading manifest.

They have restarted their ipads.

Both can be contacted in discord.

**Comment by TarekA112** [comment]
Encountered same problem, the same time Toad mentioned it on discord.
This only happened temporarily during transition from V1.1.6 when V1.1.7.
No longer happens
