### ISSUE TITLE
All buttons fade out, but only shooting button should

### ISSUE THREAD

**Issue by FlorianStronk** [koyoki/fof-issues#19]
When player starts running all buttons fade out, but  stance and scope button remain functional even in faded out state.

Only shooting buttons should disappear.

**Comment by davidhasovic** [comment]
They are all meant to fade out? This was the plan.

**Comment by FlorianStronk** [comment]
You need to try it as follows: play with one of the "buttons on screen
settings", run and try to get into prone or bring up your sights as fast as
possible. If you do it several times you will notice that you sometimes
need to wait a bit until the buttons that you need to press appear again.

On 24 June 2016 at 17:12, davidhasovic <notifications@github.com> wrote:

> They are all meant to fade out? This was the plan.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/koyoki/fof-issues/issues/19#issuecomment-228389090>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGSD0mJ1kxW0v_LqLrtpoHsJGjJPL4gFks5qPAHsgaJpZM4HoSNb>
> .
>



-- 
-- 
Florian Stronk
Koyoki Ltd
@ Red Quarters,
1-3 Rivington St, London, EC2A 3DT
mobile : + 44 (0) 7804 707483
*twitter: *florianstronk | skype : fstronkmobile

**Comment by TarekA112** [comment]
When in right hand settings, now all buttons half fade away when your soldier runs.
+ All buttons stay active when you run except for shoot button.
This scenario ist correct and logical.
Issue can be closed.
