### ISSUE TITLE
Can use consumables post-mortem

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#28]
V1.1.7
After you are killed, when watching others playing, you are still able to tap and use consumables.
![img_1926](https://cloud.githubusercontent.com/assets/17575376/13509413/2eaba066-e183-11e5-8830-8c074fc96fc4.PNG)

**Comment by TarekA112** [comment]
Fixed in V1.1.7

**Comment by TarekA112** [comment]
V1.1.7
Apologies, closed in error. Still happening for me.

**Comment by jorgebarredo** [comment]
It will be fixed in 1.1.8

**Comment by TarekA112** [comment]
Consumables icons no longer appear in post-mortem screen. 
Fixed in v1.1.9
