### ISSUE TITLE
Scope sun reflection error

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#31]
V1.1.7
Scope reflection still active after enemy down. May be confusing for opponents.
![img_1937](https://cloud.githubusercontent.com/assets/17575376/13536778/974dbbca-e239-11e5-94f1-ecf8ccd25a32.PNG)

**Comment by jorgebarredo** [comment]
Should be fixed in V1.1.8. This should not happen in multiplayer anyway.

**Comment by TarekA112** [comment]
Fixed/non-issue
Cannot replicate in multiplayer.
