### ISSUE TITLE
Water appears under map surface

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#33]
V1.1.7
When you stand/crouch/lay down against hill or sloped surface and pan camera around, water detail appears under map surface. This issue is consistent throughout every map.
![img_1958](https://cloud.githubusercontent.com/assets/17575376/13550953/8ca5c094-e321-11e5-8842-1e58a9ee7b5f.PNG)
![img_1968](https://cloud.githubusercontent.com/assets/17575376/13550954/8ca648de-e321-11e5-8443-09f78de52d57.PNG)
![img_1969](https://cloud.githubusercontent.com/assets/17575376/13550955/8ca9579a-e321-11e5-9e8d-334d5bc20be3.PNG)
![img_1970](https://cloud.githubusercontent.com/assets/17575376/13550956/8ca9770c-e321-11e5-9cf5-bbfd7c9e1190.PNG)

**Comment by jorgebarredo** [comment]
We have to improve the camera system and not allow it to go inside the game objects.

**Comment by jorgebarredo** [comment]
Should be better in V1.1.8.

**Comment by TarekA112** [comment]
Fixed
Can no longer replicate in 1.1.9
