### ISSUE TITLE
Water surface disappears

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#38]
Minor issue, can be dismissed
When lying down in river bed, panning camera around causes water to disappear. This proves useful for shooting but aesthetically does not look right. Like river bed is dry. 
![img_2032](https://cloud.githubusercontent.com/assets/17575376/13650855/9cf7c58c-e63c-11e5-8542-061fc80fb6e6.PNG)
![img_2033](https://cloud.githubusercontent.com/assets/17575376/13650863/a3088c68-e63c-11e5-8655-a2418302a28a.PNG)
![img_2034](https://cloud.githubusercontent.com/assets/17575376/13650868/a4934802-e63c-11e5-996b-4742eb545495.PNG)

**Comment by digicub** [comment]
We should prevent prone when in water, as your head also goes beneath the surface

**Comment by TarekA112** [comment]
No longer happens on NAM map. Water surface appears when below surface
