### ISSUE TITLE
SFX goes on after game session ends

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#39]
Sand/grit/crawling sound (not sure) still goes on after session ends, when you are in the stat screen.

**Comment by davidhasovic** [comment]
Is this still the case?

**Comment by TarekA112** [comment]
Yes still happens.
Run with a soldier 5 seconds before timer ends. 
You can still hear footsteps in the stat screen

**Comment by TarekA112** [comment]
Fixed
