### ISSUE TITLE
Unable to focus shot if shot button is pressed quickly after scope

### ISSUE THREAD

**Issue by FlorianStronk** [koyoki/fof-issues#43]
use sniper
hit scope button and immeditaley (as fast as you can) press shoot button.

The dispersion cross should shrink but it doesnt until you cancel the shot and tap and hold the shoot button again.

**Comment by davidhasovic** [comment]
florian is this still the case?

**Comment by FlorianStronk** [comment]
tarek can you test this please

On 24 June 2016 at 17:19, davidhasovic <notifications@github.com> wrote:

> florian is this still the case?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/koyoki/fof-issues/issues/43#issuecomment-228391000>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGSD0mfLPR4XK-bPia0B_aBgs8A0-zOOks5qPAOogaJpZM4Ht4TQ>
> .
>



-- 
-- 
Florian Stronk
Koyoki Ltd
@ Red Quarters,
1-3 Rivington St, London, EC2A 3DT
mobile : + 44 (0) 7804 707483
*twitter: *florianstronk | skype : fstronkmobile

**Comment by TarekA112** [comment]
I can't replicate this.
Crosshair shrinks/focus perfectly immediately after scope engaged.
No longer issue @ v1.2

**Comment by TarekA112** [comment]
Could never replicate this issue on Iphone6 or on the  ipadminis until i tried on Ipad Air. Seems to happen 1 in 5 times.
Use ipad air to replicate issue:
- Select sniper
- Quickly press on scope followed by shoot (keep finger pressed on shoot button).

**Comment by TarekA112** [comment]
Open Bug.
Need to be moved to Trello
