### ISSUE TITLE
Observation shelter design error

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#45]
inside this observation shelter, there is a miniature hill with a fence. This looks like a design error.
![img_2253](https://cloud.githubusercontent.com/assets/17575376/13882541/c90b9c56-ed1d-11e5-9371-60644d9fe9f5.PNG)
![img_2256](https://cloud.githubusercontent.com/assets/17575376/13882542/c90e40dc-ed1d-11e5-8707-1d41358d945c.PNG)

**Comment by digicub** [comment]
This will be out of bounds to the player once we have implemented it. But will leave the bug up until then.
