### ISSUE TITLE
Soldier levitates

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#49]
When lying down against a hill, rock or other steeped surface and pan camera around, soldier looks like he levitates above ground surface.
![img_2060](https://cloud.githubusercontent.com/assets/17575376/13882951/6e2a28dc-ed1f-11e5-9d94-7d75a753cd42.PNG)
![img_2061](https://cloud.githubusercontent.com/assets/17575376/13882952/6e2ddca2-ed1f-11e5-9c63-d3287191bc03.PNG)
![img_2118](https://cloud.githubusercontent.com/assets/17575376/13882953/6e350d74-ed1f-11e5-8165-6f0309bbca1d.PNG)

**Comment by davidhasovic** [comment]
I imagine this is still the case, right?

**Comment by TarekA112** [comment]
Yes, still case @v1.2

![img_3826](https://cloud.githubusercontent.com/assets/17575376/16345238/c6c4bf00-3a38-11e6-9d4a-423d0fa54ce5.PNG)

**Comment by TarekA112** [comment]
Open Bug.
Need to be moved to Trello
