### ISSUE TITLE
Exterior notification banners

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#5]
V 1.1.6
Exterior notifcation banners, for example Whatapp messages received while playing, leave their print where they appear.
![img_1800](https://cloud.githubusercontent.com/assets/17575376/13437967/b8f5cd92-dfde-11e5-861e-eb132ce25abc.PNG)

**Comment by jorgebarredo** [comment]
I think this is the case always in 16:9 devices, nothing to do with notifications.

**Comment by TarekA112** [comment]
@jorgebarredo 
Do i close this issue and raise as new one?

**Comment by jorgebarredo** [comment]
No need, I think it is clear enough.

**Comment by jorgebarredo** [comment]
Should be fixed in v1.1.8
