### ISSUE TITLE
Path too steep

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#58]
The drawn path shown below on the Nam map is too steep and impossible to climb.
So path is useless.
![img_2353](https://cloud.githubusercontent.com/assets/17575376/13919581/3c033cec-ef66-11e5-8f8a-873c6c99f297.PNG)
![img_2342](https://cloud.githubusercontent.com/assets/17575376/13919596/4fed87bc-ef66-11e5-949f-014be10c2e71.PNG)

**Comment by digicub** [comment]
Fixed. Aslo, nam is currently being art treated
