### ISSUE TITLE
iPhone6 can't tap battle 

### ISSUE THREAD

**Issue by FlorianStronk** [koyoki/fof-issues#67]
When you open game for the first time and tap the battle button the screen schnages to the help & tutorial sub menu screen. There should now be the tutorial prompt visible, instead there is a blank screen.
One you tap the tutorial menu item on the left  the pop up shows up eventually and only after you have ansered that prompt one can actually tap the battle button so taht you can join a game.
This video shows that this is clearly a show stopper:
https://www.dropbox.com/s/qm1guwl5qlzjjh5/Tutorialpopup.mp4?dl=0

**Comment by davidhasovic** [comment]
Is this still relevant at this point, if not please close.

**Comment by TarekA112** [comment]
The UI will completely change so all the "sub menu screens" and "tutorial menu on top left" is now irrelevant. 
Will keep track of this issue and raise if still relevant in near future.
