### ISSUE TITLE
After signing out nad logging in UI elements that should not be there remain on screen

### ISSUE THREAD

**Issue by FlorianStronk** [koyoki/fof-issues#68]
to reproduce sign out and back in, the result can be seen on the image: one has to restart the game to get thongs back to normal

![image](https://cloud.githubusercontent.com/assets/6587346/14649049/41d69e30-065d-11e6-828b-b9e0d1ecfc8e.png)

**Comment by TarekA112** [comment]
Issue based on old UI. Can close
