### ISSUE TITLE
Scope reflection issue in scope mode 

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#69]
When you and your opponent are in scope mode, scope reflection only shows when you move or crouch/prone. it does not appear when immobile.
![img_3179](https://cloud.githubusercontent.com/assets/17575376/14993315/241f8c3e-1162-11e6-95a7-a8461bce86b4.PNG)
![img_3180](https://cloud.githubusercontent.com/assets/17575376/14996928/39862eea-1174-11e6-982e-4d5f3dc2802b.PNG)

**Comment by TarekA112** [comment]
Issue still happening.
Additionaly you should not see scope reflection when soldier behind objects.

**Comment by DanielZ15** [comment]
Adding to that, the scope should not only dim but shut off when behind solid objects. Often you can still see it dimming when it's already completely behind a hill or a soldier

**Comment by DanielZ15** [comment]
Moving this to Medium in order to have only 5 open unfixed high priority issues.

**Comment by TarekA112** [comment]
Scope reflection now removed completely.

**Comment by TarekA112** [comment]
Fixed
