### ISSUE TITLE
Enemy soldier disappears 

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#73]
Enemy soldiers often disappear from view while they are standing still but come back when you move around.
Look at the examples below:

**Example1**
![img_0072](https://cloud.githubusercontent.com/assets/17575376/16309841/17abee48-3962-11e6-913f-1de99838c95c.PNG)
![img_0073](https://cloud.githubusercontent.com/assets/17575376/16309860/2654cf96-3962-11e6-8288-9e8de0bd248e.PNG)

**Example2**
![img_0075](https://cloud.githubusercontent.com/assets/17575376/16309907/535cf32e-3962-11e6-97d3-3c2f37b31bbe.PNG)
![img_0076](https://cloud.githubusercontent.com/assets/17575376/16309921/5b9dd33c-3962-11e6-9096-172f3c8f8e53.PNG)
![img_0077](https://cloud.githubusercontent.com/assets/17575376/16309933/65581af4-3962-11e6-9fe5-44dc08891f82.PNG)

**Example 3**
![img_0001](https://cloud.githubusercontent.com/assets/17575376/16364753/a7221012-3be6-11e6-925c-ffd5e459e53f.JPG)

**Comment by jorgebarredo** [comment]
Spotting system was broken. Should be fixed now.

**Comment by TarekA112** [comment]
Tested and fixed in 1.2.o
Can no longer replicate issue
