### ISSUE TITLE
No SFX for Russian sniper fire

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#74]
The Russian sniper's weapon does not always produce noise when fired.
Seems like noise is produced more often in scope mode.

**Comment by rjkward** [comment]
This soldier was missing audio files for fire and reload so only the bullet impact sound was playing. Also fixed a related bug where a low pass filter curve was flipped for all players, causing nearby sounds for weapon fire to be rendered almost inaudible.

**Comment by TarekA112** [comment]
Tested. Issue fixed @ 1.2.0
