### ISSUE TITLE
Post-Battle Statistics/Score Screen Display Errors

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#78]
- Wrong text prompted, in this case player lost. Should not display "Victory".

- "Player spotted: 3” is displayed when i never spotted anyone (this could be linked to bug #73) 

![img_0496](https://cloud.githubusercontent.com/assets/17575376/16364738/6f10a18e-3be6-11e6-97c3-d6075534799e.PNG)

**Comment by bfield** [comment]
Head shot stat not correct. (always zero)

**Comment by bfield** [comment]
Sniper levels issue. all soldier body parts are being assigned "other" body part type, this means that all hits are treated as other and not the corresponding body part, ie head, leg etc. 
Damage is calcualting correctly (more damage for a headshot) however the endgame stats count all hits as body.

**Comment by bfield** [comment]
After chatting with Andy i have removed the "players spotted" stat from the end game screen. The stat is not fully realized in this case and we don't believe it is a good metric to show at this stage.

**Comment by TarekA112** [comment]
Hold this for now, we will review this issue in group meeting on monday, cheers.

**Comment by TarekA112** [comment]
- PLayer spotted stat removed (was pointless)
- Correct post game status (victory/defeat) now appears.
Fixed
