### ISSUE TITLE
"YOU HAVE BEEN SPOTTED" not responding to situation.

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#80]
When opponent catches you in his sight, the “you have been spotted” alert does not always appear in time.
It is delayed, even when opponent is sometimes very close.
This issue could possibly be linked to bug #73

**Comment by davidhasovic** [comment]
would like to see this replicated.

**Comment by TarekA112** [comment]
Can no longer replicate.
Can be closed
