### ISSUE TITLE
Last player stays on map when all other players drop off server.

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#83]
If there are only 2 opposing soldiers left on map and one drops off server (e.g. loses connection, runs out of battery etc..), the last player stays on the map with no more opposition.

Furthermore, happens that app starts acting erratically for this last player (buttons move by themselves etc…)

Logically last player should win and return to lobby when this happens. 

Or there should be a brief pause to give a chance to other player to be fished back into session.

**Comment by davidhasovic** [comment]
There should be a reconnection timer limit, if beyond that the player should loose the game.

**Comment by TarekA112** [comment]
This was raised before reconnection process was implemented.
No longer happens.
