### ISSUE TITLE
Automatic relaunch of battle session

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#85]
After a battle, if you stay too long on the final score/stats screen a battle session is “sometimes” automatically relaunched without even going back to the UI and hitting the Battle button again. 

Meaning you go straight from the score/stats screen to the battle lobby screen.

Note: Not a consistent issue but has happened often enough.

**Comment by davidhasovic** [comment]
You need to be able to replicate this.

**Comment by TarekA112** [comment]
HAs not been happening since. Can no longer replicate
Ok to close
