### ISSUE TITLE
Movement SFX too low

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#88]
The level of sound of the movement SFX (walking, running, prone, crawling) is much lower than other SFX such as water, reloading, firing etc…

You really need to max your device volume to hear the movement SFX because it is drowned by other SFX.

Even with earphones

**Comment by rjkward** [comment]
I think the problem may more be that the weapon sound effects are too loud. I can mess around with the sliders but I'd rather let someone with more experience of audio balancing decide what the overall mix should be.

**Comment by DanielZ15** [comment]
Fair enough. Audio is it's own thing indeed. I'll close the issue for now.
