### ISSUE TITLE
Fall damage triggered even at very low heights.

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#90]
Max/Min height should be established for fall damage.
I receive fall damage at heights as low as images below.
![img_3876](https://cloud.githubusercontent.com/assets/17575376/16365136/2d84f5b8-3bef-11e6-82c6-04a9beb363b8.PNG)
![img_3878](https://cloud.githubusercontent.com/assets/17575376/16365138/39917caa-3bef-11e6-8608-21febc51acb7.PNG)
![img_3882](https://cloud.githubusercontent.com/assets/17575376/16365360/cf3d5408-3bf5-11e6-9f77-2e9a39611e78.PNG)

**Comment by davidhasovic** [comment]
should be fixed please test

**Comment by TarekA112** [comment]
Issue fixed
