### ISSUE TITLE
Scorecard needs repositioning for Iphone6 display 

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#92]
@ 750 x 1334
When display more than 4 players. 
![img_3930](https://cloud.githubusercontent.com/assets/17575376/16450373/7aa44496-3df4-11e6-94d9-d35dd088e282.PNG)

**Comment by jorgebarredo** [comment]
Should be ok, now

**Comment by TarekA112** [comment]
issue still happening on iphone 6
![img_3963](https://cloud.githubusercontent.com/assets/17575376/16488537/e65b60f0-3ec8-11e6-9ad6-689630236410.PNG)

**Comment by TarekA112** [comment]
Fixed

**Comment by TarekA112** [comment]
Fixed
