### ISSUE TITLE
Need to remove or better grey out switch player buttons in spectator mode when can only follow one (when there's one team mate left)

### ISSUE THREAD

**Issue by DanielZ15** [koyoki/fof-issues#95]
![img_2102](https://cloud.githubusercontent.com/assets/12484473/16595492/4b92f0ce-42e7-11e6-807f-fe1924be19e0.PNG)

**Comment by rjkward** [comment]
Fixed, also resized buttons so they are symmetrical.

**Comment by rjkward** [comment]
We encountered a related bug while testing the networking. If the following occur in order:

player1 disconnects
player1 is killed while they are disconnected
player1 reconnects and begins to spectate player2
player2 is killed just as player1 is loading in

Then player 1 will we able to switch to and from player2's corpse as though it were still a live player. I believe I have fixed this but it has not been tested.

**Comment by TarekA112** [comment]
Initial issue fixed.
